image: docker:latest

stages:
  - "Validate"
  - "Analyze"
  - "DevOps"

##
## Validate
##
PSScriptAnalyzer:
  stage: "Validate"
  image: cardboardci/psscriptanalyzer:edge
  script:
    - PSScriptAnalyzer -Path build/

# hadolint:
#   stage: "Validate"
#   image: cardboardci/hadolint
#   script:
#     - hadolint Dockerfile*

##
## Release
##
azure:
  stage: "DevOps"
  image: cardboardci/vsts:edge
  script:
    - vsts login -i ${AZDEVOPS_INSTANCE} --token "${AZDEVOPS_TOKEN}"
    - vsts build queue -i ${AZDEVOPS_INSTANCE} --project "CardboardCI" --definition-name "${CI_PROJECT_NAME}"
  only:
    - master