image: docker:latest

stages:
  - "Validate"
  - "Analyze"

##
## Validate
##
PSScriptAnalyzer:
  stage: "Validate"
  image: cardboardci/psscriptanalyzer:edge
  script:
    - Invoke-ScriptAnalyzer -Path build/

# hadolint:
#   stage: "Validate"
#   image: cardboardci/hadolint
#   script:
#     - hadolint Dockerfile*