pool:
  vmImage: 'windows-2019'

trigger: none

steps:
- task: Docker@1
  displayName: Login
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: DockerHub
    command: login

- task: onlyutkarsh.gitlab-integration.gitlab-downloadrepo-task.downloadgitlabrepository@1
  displayName: 'Download Repository'
  inputs:
    connection: Gitlab
    definition: 10343993
    downloadPath: '$(Build.Repository.LocalPath)/r'

- task: PowerShell@2
  displayName: Setup
  inputs:
    targetType: filePath
    filePath: '$(Build.Repository.LocalPath)/r/.docker/Setup.ps1'
    workingDirectory: '$(Build.Repository.LocalPath)/r'

- task: PowerShell@2
  displayName: Build
  inputs:
    targetType: filePath
    filePath: '$(Build.Repository.LocalPath)/r/build/Run.ps1'
    workingDirectory: '$(Build.Repository.LocalPath)/r'
