pool:
  vmImage: 'windows-2019'

steps:
- task: Docker@1
  displayName: Login
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: DockerHub
    command: login

- task: PowerShell@2
  displayName: Setup
  inputs:
    targetType: filePath
    filePath: '$(Build.Repository.LocalPath)/r/.docker/Setup.ps1'
    workingDirectory: '$(Build.Repository.LocalPath)/r'

- task: PowerShell@2
  displayName: Build
  inputs:
    targetType: filePath
    filePath: '$(Build.Repository.LocalPath)/r/build/Run.ps1'
    workingDirectory: '$(Build.Repository.LocalPath)/r'
