pool:
  vmImage: 'win2016-vs2017'

steps:
- task: Docker@1
  displayName: Login
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: DockerHub
    command: login

- task: PowerShell@2
  displayName: Setup
  inputs:
    targetType: filePath
    filePath: '.docker/Setup.ps1'

- task: PowerShell@2
  displayName: Build
  inputs:
    targetType: filePath
    filePath: 'build/Run.ps1'
